default:
  before_script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install -r requirements.txt

stages:
  - test

test:
  stage: test
  script: make test

typecheck:
  stage: test
  script: make typecheck

lint:
  stage: test
  script: make lint
